[Journey 2.0] [ORM] [Change] Remove menção de SOLID no README
betrybe/sd-0x-project-blogs-api pull request #24
Opened 2021-09-13 14:51 UTC by JefersonSchimuneck

Referente a task [854](https://dev.azure.com/betrybe/CURR%C3%8DCULO/_sprints/taskboard/Back-end/CURR%C3%8DCULO/Sprint%2084?workitem=854) do DevOps

Rubrica

**Contexto**: O bloco deste projeto introduzia os conceitos SOLID, porém este conceito foi retirado e será ensinado em blocos posteriores.

**Alterações**

- [x] Remove menção de SOLID no README

2021-09-13 21:11 UTC, vinicius-vasconcelos requested changes

2021-09-13 21:11 UTC, vinicius-vasconcelos commented on README.md
> +Você vai arquiteturar, desenvolver uma API de um CRUD posts de blog (com o sequelize). Começando pela API, você vai desenvolver alguns endpoints (seguindo os princípios do REST) que estarão conectado
```suggestion
Você vai arquiteturar e desenvolver uma API de um CRUD posts de blog (com o Sequelize). Começando pela API, você vai desenvolver alguns endpoints (seguindo os princípios do REST) que estarão conectados ao seu banco de dados.
```

2021-09-13 21:12 UTC, vinicius-vasconcelos approved these changes

2021-09-15 11:20 UTC, tiagaoalb approved these changes

2021-11-25 15:36 UTC, merged